# Global variables used in data.table NSE
# Declared to avoid R CMD check NOTEs

utils::globalVariables(c(
  ".",
  "..keep_cols",
  # --- personnel / contract columns ---
  "active_flag",
  "age",
  "contract_days",
  "effective_end",
  "pension",
  "personnel_id",
  "priority_rank",
  "retire",
  "tenure_days",
  "tenure_years",
  # --- hiring ---
  "flow_demand",
  "current_stock",
  "target_stock",
  "stock_demand",
  "total_hires",
  "exit_count",
  "head",
  "hiring_rate",
  "n_hires",
  # --- movement / promotions / transfers ---
  ".from_group",
  ".group_key",
  ".current_group_key",
  ".hist_group_key",
  ".new_salary",
  ".pid",
  "adj_prob",
  "avg_prob",
  "earliest_date",
  "expected_n",
  "from_group",
  "max_salary",
  "movement_type",
  "n_movers",
  "n_moves",
  "n_pop",
  "period_key",
  "period_prob",
  "salary_after",
  "salary_before",
  "salary_diff",
  "salary_ratio",
  "time_in_grade",
  "to_group",
  "total_outflow",
  # --- retirement / pension ---
  "i.age",
  "i.tenure_years",
  "pension_type",
  # --- plotting ---
  ".data",
  "effect",
  "effect_label",
  "fill_dir",
  "metric",
  "metric_label",
  "value",
  # --- scenario / horizon columns ---
  "is_baseline",
  "period_date",
  "scenario",
  "scenario_id",
  "scenario_label",
  "wage_bill_end"
))
